### PR TITLE
Rebase branch package_as_npm to master 1.3

### PR DESCRIPTION
**Pull request by CapOM**
Just rebase

### CODE REVIEW

**Comment by robgonnella** [comment]
Why are all the initial packaging commits included?

**Comment by CapOM** [comment]
Rebase done

**Comment by CapOM** [comment]
> Why are all the initial packaging commits included?

I had to wait for the other MR to be merged, now I rebased again and they are gone

**Comment by CapOM** [comment]
Hi @robgonnella , I am closing this MR because I realized you already cherry picked these commits and omitted those reverted. I just realized that because there were not in master branch. So let's not touch the package-as-npm like this for now. Thx!

**Pull request closed without merging**
